### PR TITLE
Economy initial helper function implementation

### PR DESCRIPTION
**Pull request by invaderjon**
This should cover most of the basic functionality required to get the economy working, minus balance expiration tracking.

### CODE REVIEW

**Comment by invaderjon** [comment]
The remainder of the base legacy economy functionality is implemented with this new update. The point values and time limits are not the same as the original implementation and are merely placeholders. All of them can be configured within the data/economy folder.

The core feature set includes:
- checkin
- custom commands
- fine (mod only)
- passive point earning
- profile
- raffle
- regularly scheduled cleanup
- rent-a-role
- result pagination
- richest
- tag
- tags
- timezone management
- transfer money

Debug commands include:
- additem
- clearbalances
- clearinventory
- clearlastcheckin
- debugprofile
- econdummy
- gimme
- inventory
- lastcheckin
- oodlesofcommands
- oodlesoftags
- takeit
- shutupandtakemymoney

All functionality has been personally tested by me, but could benefit from direct user testing to work out any mixed kinds. I'm sure that there are probably still a few bugs present given the change's size.

**Comment by invaderjon** [comment]
I "prettified" the commands a bit and added additional information for the more complex commands: tag, mycom, and rentarole. Integrate a new help command called helpshop, which displays information on all of the economy related commands. In addition, add information for fine to the moderator help command.

**Comment by invaderjon** [comment]
Last change: I added a small intro in the shop command that briefly explains how to earn Starbucks. I intentionally left out specifics so we can add them later after we figure them out.

**Comment by fizray** [comment]
Is there any bug in the code?

**Comment by invaderjon** [comment]
@GamerPaprika4785, there are almost certainly some bugs, but I did manually go down every common path and tested every sub command and every case the best that I could. I imagine any remaining bugs are probably edge case or due to unexpected behavior user.

**Comment by CorruptedPhazite** [comment]
@GamerPaprika4785 there are always bugs

**Pull request merged**
